In [13]:
#install pyspark in google colab
!pip install pyspark

#import SparkSeason
from pyspark.sql import SparkSession

#create a SparkSession  (attribute-argument(module)-method-package-endspace)
spark=SparkSession.builder.appName("Big Data Tools Overview").getOrCreate()

#Create a simple dataframe
dataframe=spark.createDataFrame([("Alice",25),("Bob",30),("Charlie",35)],["Name","Age"])

#show the dataframe
dataframe.show()

Requirement already satisfied: pyspark in /usr/local/lib/python3.10/dist-packages (3.5.3)
Requirement already satisfied: py4j==0.10.9.7 in /usr/local/lib/python3.10/dist-packages (from pyspark) (0.10.9.7)
+-------+---+
|   Name|Age|
+-------+---+
|  Alice| 25|
|    Bob| 30|
|Charlie| 35|
+-------+---+

In [9]:
#import necessary libraries
import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
import time

#load the dataset into a pandas dataframe
df=pd.read_csv('taxi_zones.csv')

#display the first few rows of the dataset
print("Sample of the dataset:")
print(df.head())


print(df.shape)

#step 2:Volume - How large is the dataset
print("\nDataset Volume:")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print(f"Memory Usage: {df.memory_usage(deep=True).sum()/(1024**2):.2f} MB")

#Step 3:Variety - What types of data are present?
print("\nDataset Variety(Data Types):")
print(df.dtypes)

#Step 4:Basic exploratory Analysis
print("\nBasic Statistics:")
df.describe()
df.info()

#velocity
print("\nSimulating data generation(streaming):")
for i in range(5): #stream 5 batches
  sample_data=df.sample(5)  #stream 5 random rows
  print(f"\nBatch {i+1}:\n", sample_data)
  time.sleep(2)  #wait for 2 seconds to simulate streaming

#step 5:Discussion on the 5 V's
#relate the observation to volume,variety,velocity,veracity,value

Sample of the dataset:
              X              Y  OBJECTID  Shape_Leng  Shape_Area  \
0  9.352230e+05  190535.052575         1    0.116357    0.000782
1  1.032516e+06  167292.493195         2    0.433470    0.004866
2  1.025883e+06  254779.600631         3    0.084341    0.000314
3  9.906188e+05  203105.532318         4    0.043567    0.000112
4  9.314680e+05  139837.478389         5    0.092146    0.000498

                      zone  LocationID        borough   Latitude  Longitude
0           Newark Airport           1            EWR  35.475594 -83.290731
1              Jamaica Bay           2         Queens  35.742300 -90.562330
2  Allerton/Pelham Gardens           3          Bronx  33.293157 -86.767961
3            Alphabet City           4      Manhattan  40.724545 -73.979050
4            Arden Heights           5  Staten Island  39.809279 -75.486587
(263, 10)

Dataset Volume:
Number of rows: 263
Number of columns: 10
Memory Usage: 0.05 MB

Dataset Variety(Data Types):
X             float64
Y             float64
OBJECTID        int64
Shape_Leng    float64
Shape_Area    float64
zone           object
LocationID      int64
borough        object
Latitude      float64
Longitude     float64
dtype: object

Basic Statistics:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   X           263 non-null    float64
 1   Y           263 non-null    float64
 2   OBJECTID    263 non-null    int64
 3   Shape_Leng  263 non-null    float64
 4   Shape_Area  263 non-null    float64
 5   zone        263 non-null    object
 6   LocationID  263 non-null    int64
 7   borough     263 non-null    object
 8   Latitude    263 non-null    float64
 9   Longitude   263 non-null    float64
dtypes: float64(6), int64(2), object(2)
memory usage: 20.7+ KB

Simulating data generation(streaming):

Batch 1:
                 X              Y  OBJECTID  Shape_Leng  Shape_Area  \
53   9.833923e+05  189565.846166        54    0.076219    0.000132
198  1.016499e+06  227862.063599       199    0.077809    0.000289
240  1.012887e+06  258436.323758       241    0.068765    0.000255
191  1.035459e+06  210539.653449       192    0.111965    0.000374
140  9.954097e+05  218659.383729       141    0.041514    0.000077

                      zone  LocationID    borough   Latitude  Longitude
53         Columbia Street          54   Brooklyn  39.657355 -76.371332
198          Rikers Island         199      Bronx  37.459336 -87.206541
240  Van Cortlandt Village         241      Bronx  33.236156 -93.234494
191        Queensboro Hill         192     Queens  43.524240 -71.700910
140        Lenox Hill West         141  Manhattan  31.759903 -97.102936

Batch 2:
                 X              Y  OBJECTID  Shape_Leng  Shape_Area  \
67   9.842666e+05  211937.944079        68    0.049337    0.000111
190  1.056017e+06  199613.402120       191    0.130933    0.000688
214  1.042382e+06  192258.252869       215    0.103556    0.000396
140  9.954097e+05  218659.383729       141    0.041514    0.000077
64   9.882511e+05  192619.772936        65    0.044607    0.000082

                            zone  LocationID    borough   Latitude  Longitude
67                  East Chelsea          68  Manhattan  42.391760 -71.032830
190               Queens Village         191     Queens  40.605382 -73.755133
214                South Jamaica         215     Queens  41.820851 -94.319081
140              Lenox Hill West         141  Manhattan  31.759903 -97.102936
64   Downtown Brooklyn/MetroTech          65   Brooklyn  40.645099 -73.945032

Batch 3:
                 X              Y  OBJECTID  Shape_Leng  Shape_Area  \
45   1.043322e+06  248116.498901        46    0.134475    0.000926
36   1.004784e+06  192954.140676        37    0.142810    0.000452
31   1.021695e+06  254249.634407        32    0.054267    0.000151
217  1.047463e+06  184776.570344       218    0.083701    0.000281
105  9.865347e+05  184600.143733       106    0.049211    0.000114

                          zone  LocationID   borough   Latitude  Longitude
45                 City Island          46     Bronx  40.847323 -73.786522
36              Bushwick South          37  Brooklyn  37.329217 -86.364699
31                   Bronxdale          32     Bronx  40.849736 -73.864682
217  Springfield Gardens North         218    Queens  33.615710 -81.102040
105                    Gowanus         106  Brooklyn  33.173737 -90.223419

Batch 4:
                 X              Y  OBJECTID  Shape_Leng  Shape_Area  \
255  9.955867e+05  198307.282684       256    0.067915    0.000169
108  9.418092e+05  139267.338614       109    0.178268    0.001170
220  9.616704e+05  165251.183527       221    0.166218    0.000890
92   1.028064e+06  208639.269516        93    0.170998    0.000594
244  9.556121e+05  168264.897868       245    0.095983    0.000466

                             zone  LocationID        borough   Latitude  \
255                 Williamsburg          256       Brooklyn  28.414451
108                   Great Kills         109  Staten Island  34.817795
220                     Stapleton         221  Staten Island  33.181447
92   Flushing Meadows-Corona Park          93         Queens  39.112510
244                 West Brighton         245  Staten Island  39.942984

      Longitude
255  -81.442849
108 -103.354685
220  -82.438568
92  -100.358750
244 -104.786597

Batch 5:
                 X              Y  OBJECTID  Shape_Leng  Shape_Area  \
209  9.997091e+05  155604.686920       210    0.114852    0.000453
39   9.854099e+05  186473.826450        40    0.051851    0.000109
35   1.007386e+06  193982.900071        36    0.087051    0.000248
171  9.553781e+05  147858.167633       172    0.118476    0.000658
261  9.992531e+05  222193.818758       262    0.049064    0.000122

                       zone  LocationID        borough   Latitude  Longitude
209          Sheepshead Bay         210       Brooklyn  35.742300 -90.562330
39          Carroll Gardens          40       Brooklyn  42.042547 -94.833800
35           Bushwick North          36       Brooklyn  33.615710 -81.102040
171  New Dorp/Midland Beach         172  Staten Island  37.369814 -83.428794
261          Yorkville East         262      Manhattan  43.112850 -75.271000